name: heroku-deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.4.6
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "quiz-builder-app"
          heroku_email: "rafael.mathias@outlook.com"
    - name: Run a one-line script
      run: echo successfully run
      